### ISSUE TITLE
(mistake, pls ignore)

### ISSUE THREAD

**Issue by swyxio** [netlify-labs/netlify-nextjs#1]
https://headbangstagram.adamwathan.now.sh/

**Comment by sw-yx** [comment]
https://github.com/zeit/next.js/pull/6070#issuecomment-454846201

**Comment by swyxio** [comment]
https://github.com/zeit/next.js/pull/6070#issuecomment-454846201

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/61808340-3219c880-ae09-11e9-971f-e0b6517e842c.png)

**Comment by swyxio** [comment]
![image](https://user-images.githubusercontent.com/6764957/61808354-380fa980-ae09-11e9-8afe-1b9f2a6aa5ea.png)

**Comment by swyxio** [comment]
https://github.com/sw-yx/sw-yx.github.io/blob/master/_posts/2019-07-09-nextjs-on-netlfy.md
